export default {
  "titleLabel": "{0} ({1})",
  "repeated": "{0} (再次发生)",
  "repeatedNtimes": "{0} (发生了 {1} 次)",
  "defaultLabel": "输入",
  "caseDescription": "区分大小写",
  "wordsDescription": "全字匹配",
  "regexDescription": "使用正则表达式",
  "alertErrorMessage": "错误: {0}",
  "alertWarningMessage": "警告: {0}",
  "alertInfoMessage": "信息: {0}",
  "unbound": "未绑定",
  "aria list": "{0}. 使用导航键进行导航。",
  "clear": "清除",
  "disable filter on type": "禁用输入时筛选",
  "enable filter on type": "启用输入时筛选",
  "empty": "未找到元素",
  "found": "已匹配 {0} 个元素(共 {1} 个)",
  "ctrlKey": "Ctrl",
  "shiftKey": "Shift",
  "altKey": "Alt",
  "windowsKey": "Windows",
  "superKey": "Super",
  "ctrlKey.long": "控件",
  "shiftKey.long": "Shift",
  "altKey.long": "Alt",
  "cmdKey.long": "命令",
  "windowsKey.long": "Windows",
  "superKey.long": "Super",
  "sev.error": "错误",
  "sev.warning": "警告",
  "sev.info": "信息",
  "quickOpenAriaLabelEntry": "{0}，选取器",
  "quickOpenAriaLabel": "选取器",
  "treeAriaLabel": "快速选取器",
  "quickInput.visibleCount": "{0} 个结果",
  "collapse all": "全部折叠",
  "miSelectAll": "全选(&&S)",
  "miUndo": "撤消(&&U)",
  "miRedo": "恢复(&&R)",
  "cursors.maximum": "光标数量被限制为 {0}。",
  "diff.tooLarge": "文件过大，无法比较。",
  "label.close": "关闭",
  "no_lines": "无内容",
  "one_line": "1 行",
  "more_lines": "{0} 行",
  "header": "差异 {0}，总共 {1}: 原始，{2}，{3}；改后，{4}，{5}",
  "blankLine": "空白",
  "equalLine": "未修改 {0}，已修改 {1}: {2}",
  "insertLine": "+ 已修改 {0}: {1}",
  "deleteLine": "- 未修改 {0}: {1} ",
  "editor.action.diffReview.next": "转至下一个差异",
  "editor.action.diffReview.prev": "转至上一个差异",
  "editorConfigurationTitle": "编辑器",
  "fontFamily": "控制字体系列。",
  "fontWeight": "控制字体粗细。",
  "fontSize": "以像素为单位控制字体大小。",
  "lineHeight": "控制行高。为 0 时则通过字体大小自动计算。",
  "letterSpacing": "控制以像素为单位的字母间距。",
  "lineNumbers.off": "不显示行号。",
  "lineNumbers.on": "将行号显示为绝对行数。",
  "lineNumbers.relative": "将行号显示为与光标相隔的行数。",
  "lineNumbers.interval": "每 10 行显示一次行号。",
  "lineNumbers": "控制行号的显示。",
  "cursorSurroundingLines": "控制光标周围可见的前置行和尾随行的最小数目。在其他一些编辑器中称为“scrollOff”或“scrollOffset”。",
  "renderFinalNewline": "当文件以换行符结束时, 呈现最后一行的行号。",
  "rulers": "在一定数量的等宽字符后显示垂直标尺。输入多个值，显示多个标尺。若数组为空，则不绘制标尺。",
  "wordSeparators": "执行单词相关的导航或操作时作为单词分隔符的字符。",
  "tabSize": "一个制表符等于的空格数。在 `#editor.detectIndentation#` 启用时，根据文件内容，该设置可能会被覆盖。",
  "insertSpaces": "按 `Tab` 键时插入空格。该设置在 `#editor.detectIndentation#` 启用时根据文件内容可能会被覆盖。",
  "detectIndentation": "控制是否在打开文件时，基于文件内容自动检测 `#editor.tabSize#` 和 `#editor.insertSpaces#`。",
  "roundedSelection": "控制选区是否有圆角。",
  "scrollBeyondLastLine": "控制编辑器是否可以滚动到最后一行之后。",
  "scrollBeyondLastColumn": "控制编辑器水平滚动时可以超过范围的字符数。",
  "smoothScrolling": "控制编辑器是否在滚动时使用动画。",
  "minimap.enabled": "控制是否显示缩略图。",
  "minimap.side": "控制在哪一侧显示缩略图。",
  "minimap.showSlider": "控制是否自动隐藏缩略图滑块。",
  "minimap.renderCharacters": "渲染每行的实际字符，而不是色块。",
  "minimap.maxColumn": "限制缩略图的宽度，控制其最多显示的列数。",
  "hover.enabled": "控制是否显示悬停提示。",
  "hover.delay": "控制显示悬停提示前的等待时间 (毫秒)。",
  "hover.sticky": "控制当鼠标移动到悬停提示上时，其是否保持可见。",
  "find.seedSearchStringFromSelection": "控制是否将编辑器选中内容作为搜索词填入到查找小组件中。",
  "find.autoFindInSelection": "在执行查找操作时，在编辑器中的选中文本中还是整个文件中进行查找。",
  "find.globalFindClipboard": "控制“查找”小组件是否读取或修改 macOS 的共享查找剪贴板。",
  "find.addExtraSpaceOnTop": "控制 \"查找小部件\" 是否应在编辑器顶部添加额外的行。如果为 true, 则可以在 \"查找小工具\" 可见时滚动到第一行之外。",
  "wordWrap.off": "永不换行。",
  "wordWrap.on": "将在视区宽度处换行。",
  "wordWrap.wordWrapColumn": "在 `#editor.wordWrapColumn#` 处折行。",
  "wordWrap.bounded": "在视区宽度和 `#editor.wordWrapColumn#` 中的较小值处折行。",
  "wordWrap": "控制折行的方式。",
  "wordWrapColumn": "在 `#editor.wordWrap#` 为 `wordWrapColumn`  或 `bounded` 时，控制编辑器的折行列。",
  "wrappingIndent.none": "没有缩进。折行从第 1 列开始。",
  "wrappingIndent.same": "折行的缩进量与其父级相同。",
  "wrappingIndent.indent": "折行的缩进量比其父级多 1。",
  "wrappingIndent.deepIndent": "折行的缩进量比其父级多 2。",
  "wrappingIndent": "控制折行的缩进。",
  "mouseWheelScrollSensitivity": "对鼠标滚轮滚动事件的 `deltaX` 和 `deltaY` 乘上的系数。",
  "fastScrollSensitivity": "按下\"Alt\"时滚动速度倍增。",
  "multiCursorModifier.ctrlCmd": "映射为 `Ctrl` (Windows 和 Linux) 或 `Command` (macOS)。",
  "multiCursorModifier.alt": "映射为 `Alt` (Windows 和 Linux) 或 `Option` (macOS)。",
  "multiCursorModifier": "在通过鼠标添加多个光标时使用的修改键。“转到定义”和“打开链接”功能所需的鼠标动作将会相应调整，不与多光标修改键冲突。[阅读详细信息](https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier)。",
  "multiCursorMergeOverlapping": "当多个光标重叠时进行合并。",
  "quickSuggestions.strings": "在字符串内启用快速建议。",
  "quickSuggestions.comments": "在注释内启用快速建议。",
  "quickSuggestions.other": "在字符串和注释外启用快速建议。",
  "quickSuggestions": "控制是否在键入时自动显示建议。",
  "quickSuggestionsDelay": "控制显示快速建议前的等待时间 (毫秒)。",
  "parameterHints.enabled": "在输入时显示含有参数文档和类型信息的小面板。",
  "parameterHints.cycle": "控制参数提示菜单在到达列表末尾时进行循环还是关闭。",
  "editor.autoClosingBrackets.languageDefined": "使用语言配置确定何时自动闭合括号。",
  "editor.autoClosingBrackets.beforeWhitespace": "仅当光标位于空白字符左侧时，才自动闭合括号。",
  "autoClosingBrackets": "控制编辑器是否在左括号后自动插入右括号。",
  "editor.autoClosingQuotes.languageDefined": "使用语言配置确定何时自动闭合引号。",
  "editor.autoClosingQuotes.beforeWhitespace": "仅当光标位于空白字符左侧时，才自动闭合引号。",
  "autoClosingQuotes": "控制编辑器是否在左引号后自动插入右引号。",
  "editor.autoClosingOvertype.always": "Always type over closing quotes or brackets.",
  "editor.autoClosingOvertype.auto": "Type over closing quotes or brackets only if they were automatically inserted.",
  "editor.autoClosingOvertype.never": "Never type over closing quotes or brackets.",
  "autoClosingOvertype": "Controls whether the editor should type over closing quotes or brackets.",
  "editor.autoSurround.languageDefined": "使用语言配置确定何时自动包住所选内容。",
  "editor.autoSurround.brackets": "使用括号而非引号来包住所选内容。",
  "editor.autoSurround.quotes": "使用引号而非括号来包住所选内容。",
  "autoSurround": "控制编辑器是否应自动包住所选内容。",
  "formatOnType": "控制编辑器在键入一行后是否自动格式化该行。",
  "formatOnPaste": "控制编辑器是否自动格式化粘贴的内容。格式化程序必须可用，并且能针对文档中的某一范围进行格式化。",
  "autoIndent": "控制编辑器是否在用户键入、粘贴或移动行时自动调整缩进。必须安装包含此语言缩进规则的扩展。",
  "suggestOnTriggerCharacters": "控制在键入触发字符后是否自动显示建议。",
  "acceptSuggestionOnEnterSmart": "仅当建议包含文本改动时才可使用 `Enter` 键进行接受。",
  "acceptSuggestionOnEnter": "控制除了 `Tab` 键以外， `Enter` 键是否同样可以接受建议。这能减少“插入新行”和“接受建议”命令之间的歧义。",
  "acceptSuggestionOnCommitCharacter": "控制是否应在遇到提交字符时接受建议。例如，在 JavaScript 中，半角分号 (`;`) 可以为提交字符，能够在接受建议的同时键入该字符。",
  "snippetSuggestions.top": "在其他建议上方显示代码片段建议。",
  "snippetSuggestions.bottom": "在其他建议下方显示代码片段建议。",
  "snippetSuggestions.inline": "在其他建议中穿插显示代码片段建议。",
  "snippetSuggestions.none": "不显示代码片段建议。",
  "snippetSuggestions": "控制代码片段是否与其他建议一起显示及其排列的位置。",
  "emptySelectionClipboard": "控制在没有选择内容时进行复制是否复制当前行。",
  "copyWithSyntaxHighlighting": "控制在复制时是否同时复制语法高亮。",
  "wordBasedSuggestions": "控制是否根据文档中的文字计算自动完成列表。",
  "suggestSelection.first": "始终选择第一个建议。",
  "suggestSelection.recentlyUsed": "选择最近的建议，除非进一步键入选择其他项。例如 `console. -> console.log`，因为最近补全过 `log`。",
  "suggestSelection.recentlyUsedByPrefix": "根据之前补全过的建议的前缀来进行选择。例如，`co -> console`、`con -> const`。",
  "suggestSelection": "控制在建议列表中如何预先选择建议。",
  "suggestFontSize": "建议小部件的字号。如果设置为 `0`，则使用 `#editor.fontSize#` 的值。",
  "suggestLineHeight": "建议小部件的行高。如果设置为 `0`，则使用 `#editor.lineHeight#` 的值。",
  "tabCompletion.on": "在按下 Tab 键时进行 Tab 补全，将插入最佳匹配建议。",
  "tabCompletion.off": "禁用 Tab 补全。",
  "tabCompletion.onlySnippets": "在前缀匹配时进行 Tab 补全。在 \"quickSuggestions\" 未启用时体验最好。",
  "tabCompletion": "启用 Tab 补全。",
  "suggest.filterGraceful": "控制对建议的筛选和排序是否考虑小的拼写错误。",
  "suggest.localityBonus": "控制排序时是否提高靠近光标的词语的优先级。",
  "suggest.shareSuggestSelections": "控制是否在多个工作区和窗口间共享记忆的建议选项(需要 `#editor.suggestSelection#`)。",
  "suggest.snippetsPreventQuickSuggestions": "控制在活动代码片段内是否禁用快速建议。",
  "suggest.showIcons": "控制是否在建议中显示或隐藏图标。",
  "suggest.maxVisibleSuggestions": "控制在显示滚动条之前 IntelliSense 将显示的建议数 (最多 15个)。",
  "suggest.filtered": "控制是否应从 IntelliSense 中筛选某些建议类型。建议类型的列表可以在这里找到: https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions。",
  "suggest.filtered.method": "当设置为 `false` 时，IntelliSense 将不会显示 `method`(方法)的建议。",
  "suggest.filtered.function": "当设置为 `false` 时，IntelliSense 将不会显示 `function`(函数)的建议。",
  "suggest.filtered.constructor": "当设置为 `false` 时，IntelliSense 将不会显示 `constructor`(构造函数)的建议。",
  "suggest.filtered.field": "当设置为 `false` 时，IntelliSense 将不会显示 `field`(字段)的建议。",
  "suggest.filtered.variable": "当设置为 `false` 时，IntelliSense 将不会显示 `variable`(变量)的建议。",
  "suggest.filtered.class": "当设置为 `false` 时，IntelliSense 将不会显示 `class`(类)的建议。",
  "suggest.filtered.struct": "当设置为 `false` 时，IntelliSense 将不会显示 `struct`(结构)的建议。",
  "suggest.filtered.interface": "当设置为 `false` 时，IntelliSense 将不会显示 `interface`(接口)的建议。",
  "suggest.filtered.module": "当设置为 `false` 时，IntelliSense 将不会显示 `module`(模块)的建议。",
  "suggest.filtered.property": "当设置为 `false` 时，IntelliSense 将不会显示 `property`(属性)的建议。",
  "suggest.filtered.event": "当设置为 `false` 时，IntelliSense 将不会显示 `event`(事件)的建议。",
  "suggest.filtered.operator": "当设置为 \"false\" 时，IntelliSense 将不会显示 \"operator\" 的建议。",
  "suggest.filtered.unit": "当设置为 `false` 时，IntelliSense 将不会显示 `unit`(单位)的建议。",
  "suggest.filtered.value": "当设置为 `false` 时，IntelliSense 将不会显示 `value`(值)的建议。",
  "suggest.filtered.constant": "当设置为 `false` 时，IntelliSense 将不会显示 `constant`(常量)的建议。",
  "suggest.filtered.enum": "当设置为 `false` 时，IntelliSense 将不会显示 `enum`(枚举)的建议。",
  "suggest.filtered.enumMember": "当设置为 `false` 时，IntelliSense 将不会显示 `enumMember`(枚举成员)的建议。",
  "suggest.filtered.keyword": "当设置为 `false` 时，IntelliSense 将不会显示 `keyword`(关键字)的建议。",
  "suggest.filtered.text": "当设置为 `false` 时，IntelliSense 将不会显示 `text`(文本)的建议。",
  "suggest.filtered.color": "当设置为 `false` 时，IntelliSense 将不会显示 `color`(颜色)的建议。",
  "suggest.filtered.file": "当设置为 `false` 时，IntelliSense 将不会显示 `file`(文件)的建议。",
  "suggest.filtered.reference": "当设置为 \"false\" 时，IntelliSense 将不会显示 \"reference\" 的建议。",
  "suggest.filtered.customcolor": "当设置为 `false` 时，IntelliSense 将不会显示 `customcolor`(自定义颜色)的建议。",
  "suggest.filtered.folder": "当设置为 `false` 时，IntelliSense 将不会显示 `folder`(文件夹)的建议。",
  "suggest.filtered.typeParameter": "当设置为 \"false\" 时，IntelliSense 将不会显示 \"typeParameter\" 的建议。",
  "suggest.filtered.snippet": "当设置为 `false` 时，IntelliSense 将不会显示 `snippet`(代码片段)的建议。",
  "editor.gotoLocation.multiple": "当存在多个目标位置时, 控制 \"Go To\" 命令 (如 \"Go To Definition\") 的行为。",
  "editor.gotoLocation.multiple.peek": "显示结果的预览视图 (默认值)",
  "editor.gotoLocation.multiple.gotoAndPeek": "转到主结果并显示预览视图",
  "editor.gotoLocation.multiple.goto": "转到主结果，并对其他人启用防偷窥导航",
  "selectionHighlight": "控制编辑器是否应突出显示与所选内容类似的匹配项。",
  "occurrencesHighlight": "控制编辑器是否突出显示语义符号的匹配项。",
  "overviewRulerLanes": "控制概览标尺中同一位置可显示的提示数量。",
  "overviewRulerBorder": "控制是否在概览标尺周围绘制边框。",
  "cursorBlinking": "控制光标的动画样式。",
  "mouseWheelZoom": "按住 `Ctrl` 键并滚动鼠标滚轮时对编辑器字体大小进行缩放。",
  "cursorSmoothCaretAnimation": "控制是否启用平滑插入动画。",
  "cursorStyle": "控制光标样式。",
  "cursorWidth": "当 `#editor.cursorStyle#` 设置为 `line` 时，控制光标的宽度。",
  "fontLigatures": "启用或禁用字体连字。",
  "hideCursorInOverviewRuler": "控制是否在概览标尺中隐藏光标。",
  "renderWhitespace.selection": "仅在选定文本上呈现空白字符。",
  "renderWhitespace": "控制编辑器在空白字符上显示符号的方式。",
  "renderControlCharacters": "控制编辑器是否显示控制字符。",
  "renderIndentGuides": "控制编辑器是否显示缩进参考线。",
  "highlightActiveIndentGuide": "控制是否突出显示编辑器中活动的缩进参考线。",
  "renderLineHighlight.all": "同时突出显示导航线和当前行。",
  "renderLineHighlight": "控制编辑器的当前行进行高亮显示的方式。",
  "codeLens": "控制是否在编辑器中显示 CodeLens。",
  "folding": "控制编辑器是否启用了代码折叠。",
  "foldingStrategy": "控制计算折叠范围的策略。`auto` 将使用语言特定的折叠策略 (若可用)。`indentation` 将使用基于缩进的折叠策略。",
  "showFoldingControls": "控制是否自动隐藏导航线上的折叠控件。",
  "matchBrackets": "当选择其中一项时，将突出显示匹配的括号。",
  "glyphMargin": "控制编辑器是否应呈现垂直字形边距。字形边距最常用于调试。",
  "useTabStops": "根据制表位插入和删除空格。",
  "trimAutoWhitespace": "删除自动插入的尾随空白符号。",
  "stablePeek": "在速览编辑器中，即使双击其中的内容或者按 `Esc` 键，也保持其打开状态。",
  "dragAndDrop": "控制在编辑器中是否允许通过拖放来移动选中内容。",
  "accessibilitySupport.auto": "编辑器将使用平台 API 以检测是否附加了屏幕阅读器。",
  "accessibilitySupport.on": "编辑器将对屏幕阅读器的使用进行永久优化。",
  "accessibilitySupport.off": "编辑器将不再对屏幕阅读器的使用进行优化。",
  "accessibilitySupport": "控制编辑器是否应运行在对屏幕阅读器进行优化的模式。",
  "showUnused": "控制是否淡化未使用的代码。",
  "links": "控制是否在编辑器中检测链接并使其可被点击。",
  "colorDecorators": "控制编辑器是否显示内联颜色修饰器和颜色选取器。",
  "codeActions": "在编辑器中启用代码操作小灯泡提示。",
  "maxTokenizationLineLength": "由于性能原因，超过这个长度的行将不会被标记",
  "codeActionsOnSave.organizeImports": "控制是否在文件保存时整理 import 语句。",
  "codeActionsOnSave.fixAll": "控制是否应在文件保存时运行自动修复操作。",
  "codeActionsOnSave": "在保存时运行的代码操作类型。",
  "codeActionsOnSaveTimeout": "控制在保存文件时进行的代码操作的超时时间 (毫秒)。",
  "selectionClipboard": "控制是否支持 Linux 主剪贴板。",
  "sideBySide": "控制差异编辑器的显示方式是并排还是内联。",
  "ignoreTrimWhitespace": "控制在差异编辑器中是否把前导空格或尾随空格的改动显示为差异。",
  "largeFileOptimizations": "对大型文件进行特殊处理，禁用某些内存密集型功能。",
  "renderIndicators": "控制差异编辑器是否为添加/删除的更改显示 +/- 指示符号。",
  "accessibilityOffAriaLabel": "现在无法访问编辑器。按 Alt+F1  显示选项。",
  "plainText.alias": "纯文本",
  "noSelection": "无选择",
  "singleSelectionRange": "行 {0}, 列 {1} (选中 {2})",
  "singleSelection": "行 {0}, 列 {1}",
  "multiSelectionRange": "{0} 选择(已选择 {1} 个字符)",
  "multiSelection": "{0} 选择",
  "emergencyConfOn": "现在将 \"辅助功能支持\" 设置更改为 \"打开\"。",
  "openingDocs": "现在正在打开“编辑器辅助功能”文档页。",
  "readonlyDiffEditor": "在差异编辑器的只读窗格中。",
  "editableDiffEditor": "在一个差异编辑器的窗格中。",
  "readonlyEditor": "在只读代码编辑器中",
  "editableEditor": "在代码编辑器中",
  "changeConfigToOnMac": "若要配置编辑器，将其进行优化以最好地配合屏幕阅读器的使用，请立即按 Command+E。",
  "changeConfigToOnWinLinux": "若要配置编辑器，将其进行优化以最高效地配合屏幕阅读器的使用，按下 Control+E。",
  "auto_on": "配置编辑器，将其进行优化以最好地配合屏幕读取器的使用。",
  "auto_off": "编辑器被配置为永远不进行优化以配合屏幕读取器的使用, 而当前不是这种情况。",
  "tabFocusModeOnMsg": "在当前编辑器中按 Tab 会将焦点移动到下一个可聚焦的元素。通过按 {0} 切换此行为。",
  "tabFocusModeOnMsgNoKb": "在当前编辑器中按 Tab 会将焦点移动到下一个可聚焦的元素。当前无法通过按键绑定触发命令 {0}。",
  "tabFocusModeOffMsg": "在当前编辑器中按 Tab 将插入制表符。通过按 {0} 切换此行为。",
  "tabFocusModeOffMsgNoKb": "在当前编辑器中按 Tab 会插入制表符。当前无法通过键绑定触发命令 {0}。",
  "openDocMac": "现在按 Command+H 打开一个浏览器窗口, 其中包含有关编辑器辅助功能的详细信息。",
  "openDocWinLinux": "现在按 \"控制\" + H 打开一个浏览器窗口, 其中包含有关编辑器辅助功能的更多信息。",
  "outroMsg": "你可以按 Esc 或 Shift+Esc 消除此工具提示并返回到编辑器。",
  "showAccessibilityHelpAction": "显示辅助功能帮助",
  "inspectTokens": "开发人员: 检查令牌",
  "gotoLineLabelValidLineAndColumn": "转到第 {0} 行，第 {1} 列",
  "gotoLineLabelValidLine": "转至行 {0}",
  "gotoLineLabelEmptyWithLineLimit": "键入要导航到的介于 1 和 {0} 之间的行号",
  "gotoLineLabelEmptyWithLineAndColumnLimit": "键入 1 和 {0} 之间的字符以导航到",
  "gotoLineAriaLabel": "当前行: {0}. 转到行 {1}。",
  "gotoLineActionInput": "键入行号, 后跟可选冒号和要导航到的字符数",
  "gotoLineActionLabel": "转到行...",
  "ariaLabelEntryWithKey": "{0}、{1} ，命令",
  "ariaLabelEntry": "{0}，命令",
  "quickCommandActionInput": "键入要执行的操作的名称",
  "quickCommandActionLabel": "命令面板",
  "entryAriaLabel": "{0}，符号",
  "quickOutlineActionInput": "键入要导航到的标识符的名称",
  "quickOutlineActionLabel": "转到符号...",
  "symbols": "符号({0})",
  "modules": "模块({0})",
  "class": "类({0})",
  "interface": "接口({0})",
  "method": "方法({0})",
  "function": "函数({0})",
  "property": "属性 ({0})",
  "variable": "变量({0})",
  "variable2": "变量({0})",
  "_constructor": "构造函数 ({0})",
  "call": "调用 ({0})",
  "accessibilityHelpMessageIE": "按 Ctrl+F1 可打开辅助功能选项。",
  "accessibilityHelpMessage": "按 Alt+F1 可打开辅助功能选项。",
  "toggleHighContrast": "切换高对比度主题",
  "bulkEditServiceSummary": "在 {1} 个文件中进行了 {0} 次编辑",
  "lineHighlight": "光标所在行高亮内容的背景颜色。",
  "lineHighlightBorderBox": "光标所在行四周边框的背景颜色。",
  "rangeHighlight": "背景颜色的高亮范围，喜欢通过快速打开和查找功能。颜色不能不透明，以免隐藏底层装饰。",
  "rangeHighlightBorder": "高亮区域边框的背景颜色。",
  "caret": "编辑器光标颜色。",
  "editorCursorBackground": "编辑器光标的背景色。可以自定义块型光标覆盖字符的颜色。",
  "editorWhitespaces": "编辑器中空白字符的颜色。",
  "editorIndentGuides": "编辑器缩进参考线的颜色。",
  "editorActiveIndentGuide": "编辑器活动缩进参考线的颜色。",
  "editorLineNumbers": "编辑器行号的颜色。",
  "editorActiveLineNumber": "编辑器活动行号的颜色",
  "deprecatedEditorActiveLineNumber": "\"Id\" 已被弃用，请改用 \"editorLineNumber.activeForeground\"。",
  "editorRuler": "编辑器标尺的颜色。",
  "editorCodeLensForeground": "编辑器 CodeLens 的前景色",
  "editorBracketMatchBackground": "匹配括号的背景色",
  "editorBracketMatchBorder": "匹配括号外框的颜色",
  "editorOverviewRulerBorder": "概览标尺边框的颜色。",
  "editorGutter": "编辑器导航线的背景色。导航线包括边缘符号和行号。",
  "unnecessaryCodeBorder": "编辑器中不必要(未使用)的源代码的边框颜色。",
  "unnecessaryCodeOpacity": "非必须（未使用）代码的在编辑器中显示的不透明度。例如，\"#000000c0\" 将以 75% 的不透明度显示代码。对于高对比度主题，请使用 ”editorUnnecessaryCode.border“ 主题来为非必须代码添加下划线，以避免颜色淡化。",
  "overviewRulerRangeHighlight": "用于突出显示范围的概述标尺标记颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "overviewRuleError": "概览标尺中错误标记的颜色。",
  "overviewRuleWarning": "概览标尺中警告标记的颜色。",
  "overviewRuleInfo": "概览标尺中信息标记的颜色。",
  "overviewRulerBracketMatchForeground": "概览标尺上表示匹配括号的标记颜色。",
  "smartSelect.jumpBracket": "转到括号",
  "smartSelect.selectToBracket": "选择括号所有内容",
  "miGoToBracket": "转到括号(&&B)",
  "caret.moveLeft": "将插入点左移",
  "caret.moveRight": "将插入点右移",
  "transposeLetters.label": "转置字母",
  "actions.clipboard.cutLabel": "剪切",
  "miCut": "剪切(&&T)",
  "actions.clipboard.copyLabel": "复制",
  "miCopy": "复制(&&C)",
  "actions.clipboard.pasteLabel": "粘贴",
  "miPaste": "粘贴(&&P)",
  "actions.clipboard.copyWithSyntaxHighlightingLabel": "复制并突出显示语法",
  "quickfix.trigger.label": "快速修复...",
  "editor.action.quickFix.noneMessage": "没有可用的代码操作",
  "refactor.label": "重构...",
  "editor.action.refactor.noneMessage": "没有可用的重构操作",
  "source.label": "源代码操作...",
  "editor.action.source.noneMessage": "没有可用的源代码操作",
  "organizeImports.label": "整理 import 语句",
  "editor.action.organize.noneMessage": "没有可用的整理 import 语句操作",
  "fixAll.label": "全部修复",
  "fixAll.noneMessage": "没有可用的“全部修复”操作",
  "autoFix.label": "自动修复...",
  "editor.action.autoFix.noneMessage": "没有可用的自动修复程序",
  "quickFixWithKb": "显示修补程序({0})",
  "quickFix": "显示修补程序",
  "comment.line": "切换行注释",
  "miToggleLineComment": "切换行注释(&&T)",
  "comment.line.add": "添加行注释",
  "comment.line.remove": "删除行注释",
  "comment.block": "切换块注释",
  "miToggleBlockComment": "切换块注释(&&B)",
  "action.showContextMenu.label": "显示编辑器上下文菜单",
  "cursor.undo": "软撤消",
  "startFindAction": "查找",
  "miFind": "查找(&&F)",
  "startFindWithSelectionAction": "查找选定内容",
  "findNextMatchAction": "查找下一个",
  "findPreviousMatchAction": "查找上一个",
  "nextSelectionMatchFindAction": "查找下一个选择",
  "previousSelectionMatchFindAction": "查找上一个选择",
  "startReplace": "替换",
  "miReplace": "替换(&&R)",
  "label.find": "查找",
  "placeholder.find": "查找",
  "label.previousMatchButton": "上一个匹配项",
  "label.nextMatchButton": "下一个匹配项",
  "label.toggleSelectionFind": "在选定内容中查找",
  "label.closeButton": "关闭",
  "label.replace": "替换",
  "placeholder.replace": "替换",
  "label.replaceButton": "替换",
  "label.replaceAllButton": "全部替换",
  "label.toggleReplaceButton": "切换替换模式",
  "title.matchesCountLimit": "仅高亮了前 {0} 个结果，但所有查找操作均针对全文。",
  "label.matchesLocation": "{1} 中的 {0}",
  "label.noResults": "无结果",
  "ariaSearchNoResultEmpty": "找到 {0}",
  "ariaSearchNoResult": "为{1}找到了{0}",
  "ariaSearchNoResultWithLineNum": "{0} 在 {2} 处找到 {1}",
  "ariaSearchNoResultWithLineNumNoCurrentMatch": "{0} 已找到 {1}",
  "ctrlEnter.keybindingChanged": "Ctrl+Enter now inserts line break instead of replacing all. You can modify the keybinding for editor.action.replaceAll to override this behavior.",
  "unfoldAction.label": "展开",
  "unFoldRecursivelyAction.label": "以递归方式展开",
  "foldAction.label": "折叠",
  "foldRecursivelyAction.label": "以递归方式折叠",
  "foldAllBlockComments.label": "折叠所有块注释",
  "foldAllMarkerRegions.label": "折叠所有区域",
  "unfoldAllMarkerRegions.label": "展开所有区域",
  "foldAllAction.label": "全部折叠",
  "unfoldAllAction.label": "全部展开",
  "foldLevelAction.label": "折叠级别 {0}",
  "EditorFontZoomIn.label": "放大编辑器字体",
  "EditorFontZoomOut.label": "缩小编辑器字体",
  "EditorFontZoomReset.label": "重置编辑器字体大小",
  "hint11": "在第 {0} 行进行了 1 次格式编辑",
  "hintn1": "在第 {1} 行进行了 {0} 次格式编辑",
  "hint1n": "第 {0} 行到第 {1} 行间进行了 1 次格式编辑",
  "hintnn": "第 {1} 行到第 {2} 行间进行了 {0} 次格式编辑",
  "formatDocument.label": "格式化文档",
  "formatSelection.label": "格式化选定内容",
  "noResultWord": "未找到“{0}”的任何定义",
  "generic.noResults": "找不到定义",
  "meta.title": " – {0} 定义",
  "actions.goToDecl.label": "转到定义",
  "actions.goToDeclToSide.label": "打开侧边的定义",
  "actions.previewDecl.label": "查看定义",
  "decl.noResultWord": "未找到“{0}”的声明",
  "decl.generic.noResults": "未找到声明",
  "decl.meta.title": "– {0} 声明",
  "actions.goToDeclaration.label": "转到声明",
  "actions.peekDecl.label": "查看声明",
  "goToImplementation.noResultWord": "未找到“{0}”的实现",
  "goToImplementation.generic.noResults": "未找到实现",
  "meta.implementations.title": "– {0} 个实现",
  "actions.goToImplementation.label": "转到实现",
  "actions.peekImplementation.label": "速览实现",
  "goToTypeDefinition.noResultWord": "未找到“{0}”的类型定义",
  "goToTypeDefinition.generic.noResults": "未找到类型定义",
  "meta.typeDefinitions.title": " – {0} 个类型定义",
  "actions.goToTypeDefinition.label": "转到类型定义",
  "actions.peekTypeDefinition.label": "快速查看类型定义",
  "miGotoDefinition": "转到定义(&&D)...",
  "miGotoTypeDefinition": "转到类型定义(&&T)",
  "miGotoImplementation": "转到实现(&&I)",
  "multipleResults": "单击显示 {0} 个定义。",
  "markerAction.next.label": "转到下一个问题 (错误、警告、信息)",
  "markerAction.previous.label": "转到上一个问题 (错误、警告、信息)",
  "markerAction.nextInFiles.label": "转到文件中的下一个问题 (错误、警告、信息)",
  "markerAction.previousInFiles.label": "转到文件中的上一个问题 (错误、警告、信息)",
  "miGotoNextProblem": "下一个问题(&&P)",
  "miGotoPreviousProblem": "上一个问题(&&P)",
  "problems": "{0} 个问题(共 {1} 个)",
  "change": "{0} 个问题(共 {1} 个})",
  "editorMarkerNavigationError": "编辑器标记导航小组件错误颜色。",
  "editorMarkerNavigationWarning": "编辑器标记导航小组件警告颜色。",
  "editorMarkerNavigationInfo": "编辑器标记导航小组件信息颜色。",
  "editorMarkerNavigationBackground": "编辑器标记导航小组件背景色。",
  "showHover": "显示悬停",
  "modesContentHover.loading": "正在加载...",
  "peek problem": "速览问题",
  "checkingForQuickFixes": "正在检查快速修复...",
  "noQuickFixes": "没有可用的快速修复",
  "quick fixes": "快速修复...",
  "InPlaceReplaceAction.previous.label": "替换为上一个值",
  "InPlaceReplaceAction.next.label": "替换为下一个值",
  "lines.copyUp": "向上复制行",
  "miCopyLinesUp": "向上复制行(&&C)",
  "lines.copyDown": "向下复制行",
  "miCopyLinesDown": "向下复制一行(&&P)",
  "lines.moveUp": "向上移动行",
  "miMoveLinesUp": "向上移动一行(&&V)",
  "lines.moveDown": "向下移动行",
  "miMoveLinesDown": "向下移动一行(&&L)",
  "lines.sortAscending": "按升序排列行",
  "lines.sortDescending": "按降序排列行",
  "lines.trimTrailingWhitespace": "裁剪尾随空格",
  "lines.delete": "删除行",
  "lines.indent": "行缩进",
  "lines.outdent": "行减少缩进",
  "lines.insertBefore": "在上面插入行",
  "lines.insertAfter": "在下面插入行",
  "lines.deleteAllLeft": "删除左侧所有内容",
  "lines.deleteAllRight": "删除右侧所有内容",
  "lines.joinLines": "合并行",
  "editor.transpose": "转置光标处的字符",
  "editor.transformToUppercase": "转换为大写",
  "editor.transformToLowercase": "转换为小写",
  "editor.transformToTitlecase": "转换为词首字母大写",
  "links.navigate.executeCmd": "执行命令",
  "links.navigate.follow": "关注链接",
  "links.navigate.kb.meta.mac": "cmd + 单击",
  "links.navigate.kb.meta": "ctrl + 单击",
  "links.navigate.kb.alt.mac": "option + 单击",
  "links.navigate.kb.alt": "alt + 单击",
  "invalid.url": "此链接格式不正确，无法打开: {0}",
  "missing.url": "此链接目标已丢失，无法打开。",
  "label": "打开链接",
  "editor.readonly": "无法在只读编辑器中编辑",
  "mutlicursor.insertAbove": "在上面添加光标",
  "miInsertCursorAbove": "在上面添加光标(&&A)",
  "mutlicursor.insertBelow": "在下面添加光标",
  "miInsertCursorBelow": "在下面添加光标(&&D)",
  "mutlicursor.insertAtEndOfEachLineSelected": "在行尾添加光标",
  "miInsertCursorAtEndOfEachLineSelected": "在行尾添加光标(&&U)",
  "mutlicursor.addCursorsToBottom": "在底部添加光标",
  "mutlicursor.addCursorsToTop": "在顶部添加光标",
  "addSelectionToNextFindMatch": "将下一个查找匹配项添加到选择",
  "miAddSelectionToNextFindMatch": "添加下一个匹配项(&&N)",
  "addSelectionToPreviousFindMatch": "将选择内容添加到上一查找匹配项",
  "miAddSelectionToPreviousFindMatch": "添加上一个匹配项(&&R)",
  "moveSelectionToNextFindMatch": "将上次选择移动到下一个查找匹配项",
  "moveSelectionToPreviousFindMatch": "将上个选择内容移动到上一查找匹配项",
  "selectAllOccurrencesOfFindMatch": "选择所有找到的查找匹配项",
  "miSelectHighlights": "选择所有匹配项(&&O)",
  "changeAll.label": "更改所有匹配项",
  "parameterHints.trigger.label": "触发参数提示",
  "hint": "{0}，提示",
  "labelLoading": "正在加载...",
  "meta.titleReference": " – {0} 个引用",
  "references.action.label": "查看引用",
  "aria.oneReference": "在文件 {0} 的 {1} 行 {2} 列的符号",
  "aria.fileReferences.1": "{0} 中有 1 个符号，完整路径: {1}",
  "aria.fileReferences.N": "{1} 中有 {0} 个符号，完整路径: {2}",
  "aria.result.0": "未找到结果",
  "aria.result.1": "在 {0} 中找到 1 个符号",
  "aria.result.n1": "在 {1} 中找到 {0} 个符号",
  "aria.result.nm": "在 {1} 个文件中找到 {0} 个符号",
  "referencesFailre": "解析文件失败。",
  "referencesCount": "{0} 个引用",
  "referenceCount": "{0} 个引用",
  "missingPreviewMessage": "无可用预览",
  "noResults": "无结果",
  "peekView.alternateTitle": "引用",
  "peekViewTitleBackground": "速览视图标题区域背景颜色。",
  "peekViewTitleForeground": "速览视图标题颜色。",
  "peekViewTitleInfoForeground": "速览视图标题信息颜色。",
  "peekViewBorder": "速览视图边框和箭头颜色。",
  "peekViewResultsBackground": "速览视图结果列表背景色。",
  "peekViewResultsMatchForeground": "速览视图结果列表中行节点的前景色。",
  "peekViewResultsFileForeground": "速览视图结果列表中文件节点的前景色。",
  "peekViewResultsSelectionBackground": "速览视图结果列表中所选条目的背景色。",
  "peekViewResultsSelectionForeground": "速览视图结果列表中所选条目的前景色。",
  "peekViewEditorBackground": "速览视图编辑器背景色。",
  "peekViewEditorGutterBackground": "速览视图编辑器中装订线的背景色。",
  "peekViewResultsMatchHighlight": "在速览视图结果列表中匹配突出显示颜色。",
  "peekViewEditorMatchHighlight": "在速览视图编辑器中匹配突出显示颜色。",
  "peekViewEditorMatchHighlightBorder": "在速览视图编辑器中匹配项的突出显示边框。",
  "no result": "无结果。",
  "resolveRenameLocationFailed": "解析重命名位置时发生未知错误",
  "aria": "成功将“{0}”重命名为“{1}”。摘要: {2}",
  "rename.failed": "无法进行重命名。",
  "rename.label": "重命名符号",
  "renameAriaLabel": "重命名输入。键入新名称并按 \"Enter\" 提交。",
  "smartSelect.expand": "展开选择",
  "miSmartSelectGrow": "展开选定内容(&&E)",
  "smartSelect.shrink": "收起选择",
  "miSmartSelectShrink": "缩小选定范围(&&S)",
  "Sunday": "星期天",
  "Monday": "星期一",
  "Tuesday": "星期二",
  "Wednesday": "星期三",
  "Thursday": "星期四",
  "Friday": "星期五",
  "Saturday": "星期六",
  "SundayShort": "周日",
  "MondayShort": "周一",
  "TuesdayShort": "周二",
  "WednesdayShort": "周三",
  "ThursdayShort": "周四",
  "FridayShort": "周五",
  "SaturdayShort": "周六",
  "January": "一月",
  "February": "二月",
  "March": "三月",
  "April": "四月",
  "May": "5月",
  "June": "六月",
  "July": "七月",
  "August": "八月",
  "September": "九月",
  "October": "十月",
  "November": "十一月",
  "December": "十二月",
  "JanuaryShort": "1月",
  "FebruaryShort": "2月",
  "MarchShort": "三月",
  "AprilShort": "4月",
  "MayShort": "5月",
  "JuneShort": "6月",
  "JulyShort": "七月",
  "AugustShort": "八月",
  "SeptemberShort": "九月",
  "OctoberShort": "10月",
  "NovemberShort": "11 月",
  "DecemberShort": "12月",
  "arai.alert.snippet": "选择“{0}”后进行了其他 {1} 次编辑",
  "suggest.trigger.label": "触发建议",
  "editorSuggestWidgetBackground": "建议小组件的背景色。",
  "editorSuggestWidgetBorder": "建议小组件的边框颜色。",
  "editorSuggestWidgetForeground": "建议小组件的前景色。",
  "editorSuggestWidgetSelectedBackground": "建议小组件中所选条目的背景色。",
  "editorSuggestWidgetHighlightForeground": "建议小组件中匹配内容的高亮颜色。",
  "readMore": "阅读更多...{0}",
  "readLess": "阅读简略信息...{0}",
  "loading": "正在加载...",
  "suggestWidget.loading": "正在加载...",
  "suggestWidget.noSuggestions": "无建议。",
  "ariaCurrenttSuggestionReadDetails": "项目 {0}，文档: {1}",
  "toggle.tabMovesFocus": "切换 Tab 键移动焦点",
  "toggle.tabMovesFocus.on": "Tab 键将移动到下一可聚焦的元素",
  "toggle.tabMovesFocus.off": "Tab 键将插入制表符",
  "forceRetokenize": "开发者: 强制重新进行标记",
  "wordHighlight": "读取访问期间符号的背景色，例如读取变量时。颜色必须透明，以免隐藏下面的修饰效果。",
  "wordHighlightStrong": "写入访问过程中符号的背景色，例如写入变量时。颜色必须透明，以免隐藏下面的修饰效果。",
  "wordHighlightBorder": "符号在进行读取访问操作时的边框颜色，例如读取变量。",
  "wordHighlightStrongBorder": "符号在进行写入访问操作时的边框颜色，例如写入变量。",
  "overviewRulerWordHighlightForeground": "用于突出显示符号的概述标尺标记颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "overviewRulerWordHighlightStrongForeground": "用于突出显示写权限符号的概述标尺标记颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "wordHighlight.next.label": "转到下一个突出显示的符号",
  "wordHighlight.previous.label": "转到上一个突出显示的符号",
  "wordHighlight.trigger.label": "触发符号高亮",
  "ShowAccessibilityHelpAction": "显示辅助功能帮助",
  "GotoLineAction.label": "转到行...",
  "QuickCommandAction.label": "命令面板(&&C)...",
  "QuickOutlineAction.label": "转到“文件”中的“符号”",
  "package": "包({0})",
  "enum": "枚举({0})",
  "string": "字符串({0})",
  "file": "文件({0})",
  "array": "数组({0})",
  "number": "编号({0})",
  "boolean": "布尔值({0})",
  "object": "对象({0})",
  "key": "键({0})",
  "noSymbolsMatching": "没有匹配的符号",
  "noSymbolsFound": "找不到符号",
  "gotoSymbolHandlerAriaLabel": "键入以减少当前活动编辑器的符号",
  "cannotRunGotoSymbolInFile": "没有该文件的任何符号信息",
  "cannotRunGotoSymbol": "首先打开文本文件以转到符号",
  "editorViewAccessibleLabel": "编辑器内容",
  "defaultConfigurations.title": "默认配置替代",
  "overrideSettings.description": "针对 {0} 语言，配置替代编辑器设置。",
  "overrideSettings.defaultDescription": "针对某种语言，配置替代编辑器设置。",
  "config.property.languageDefault": "无法注册“{0}”。其符合描述特定语言编辑器设置的表达式 \"\\\\[.*\\\\]$\"。请使用 \"configurationDefaults\"。",
  "config.property.duplicate": "无法注册“{0}”。此属性已注册。",
  "moreFile": "...1 个其他文件未显示",
  "moreFiles": "...{0} 个其他文件未显示",
  "first.chord": "已按下({0})。正在等待同时按下第二个键...",
  "missing.chord": "组合键({0}, {1})不是命令。",
  "untitledWorkspace": "无标题 (工作区)",
  "workspaceName": "{0} (工作区)",
  "workbenchConfigurationTitle": "工作台",
  "multiSelectModifier.ctrlCmd": "映射为 `Ctrl` (Windows 和 Linux) 或 `Command` (macOS)。",
  "multiSelectModifier.alt": "映射为 `Alt` (Windows 和 Linux) 或 `Option` (macOS)。",
  "multiSelectModifier": "在通过鼠标多选树和列表条目时使用的修改键 (例如“资源管理器”、“打开的编辑器”和“源代码管理”视图)。“在侧边打开”功能所需的鼠标动作 (若可用) 将会相应调整，不与多选修改键冲突。",
  "openModeModifier": "控制在树和列表中怎样使用鼠标来展开子项（若支持）。对于树中的父节点，此设置将控制是使用单击还是双击来展开。注意，某些不适用于此设置的树或列表可能会忽略此项。",
  "horizontalScrolling setting": "控制列表和树是否支持在工作台中进行水平滚动。",
  "tree horizontalScrolling setting": "控制工作台中的树控件是否支持水平滚动。",
  "deprecated": "此设置已弃用，请改用“{0}”。",
  "tree indent setting": "控制树缩进(以像素为单位)。",
  "render tree indent guides": "控制树是否应呈现缩进参考线。",
  "keyboardNavigationSettingKey.simple": "简单键盘导航聚焦与键盘输入相匹配的元素。仅对前缀进行匹配。",
  "keyboardNavigationSettingKey.highlight": "高亮键盘导航会突出显示与键盘输入相匹配的元素。进一步向上和向下导航将仅遍历突出显示的元素。",
  "keyboardNavigationSettingKey.filter": "筛选器键盘导航将筛选出并隐藏与键盘输入不匹配的所有元素。",
  "keyboardNavigationSettingKey": "控制工作台中的列表和树的键盘导航样式。它可为“简单”、“突出显示”或“筛选”。",
  "automatic keyboard navigation setting": "控制列表和树中的键盘导航是否仅通过键入自动触发。如果设置为“false”，键盘导航只在执行“list.toggleKeyboardNavigation ”命令时触发，您可以为该命令指定键盘快捷方式。",
  "foreground": "整体前景色。此颜色仅在不被组件覆盖时适用。",
  "errorForeground": "错误信息的整体前景色。此颜色仅在不被组件覆盖时适用。",
  "descriptionForeground": "提供其他信息的说明文本的前景色，例如标签文本。",
  "focusBorder": "焦点元素的整体边框颜色。此颜色仅在不被其他组件覆盖时适用。",
  "contrastBorder": "在元素周围额外的一层边框，用来提高对比度从而区别其他元素。",
  "activeContrastBorder": "在活动元素周围额外的一层边框，用来提高对比度从而区别其他元素。",
  "selectionBackground": "工作台所选文本的背景颜色（例如输入字段或文本区域）。注意，本设置不适用于编辑器。",
  "textSeparatorForeground": "文字分隔符的颜色。",
  "textLinkForeground": "文本中链接的前景色。",
  "textLinkActiveForeground": "文本中链接在点击或鼠标悬停时的前景色 。",
  "textPreformatForeground": "预格式化文本段的前景色。",
  "textBlockQuoteBackground": "文本中块引用的背景颜色。",
  "textBlockQuoteBorder": "文本中块引用的边框颜色。",
  "textCodeBlockBackground": "文本中代码块的背景颜色。",
  "widgetShadow": "编辑器内小组件（如查找/替换）的阴影颜色。",
  "inputBoxBackground": "输入框背景色。",
  "inputBoxForeground": "输入框前景色。",
  "inputBoxBorder": "输入框边框。",
  "inputBoxActiveOptionBorder": "输入字段中已激活选项的边框颜色。",
  "inputOption.activeBackground": "输入字段中激活选项的背景颜色。",
  "inputPlaceholderForeground": "输入框中占位符的前景色。",
  "inputValidationInfoBackground": "输入验证结果为信息级别时的背景色。",
  "inputValidationInfoForeground": "输入验证结果为信息级别时的前景色。",
  "inputValidationInfoBorder": "严重性为信息时输入验证的边框颜色。",
  "inputValidationWarningBackground": "严重性为警告时输入验证的背景色。",
  "inputValidationWarningForeground": "输入验证结果为警告级别时的前景色。",
  "inputValidationWarningBorder": "严重性为警告时输入验证的边框颜色。",
  "inputValidationErrorBackground": "输入验证结果为错误级别时的背景色。",
  "inputValidationErrorForeground": "输入验证结果为错误级别时的前景色。",
  "inputValidationErrorBorder": "严重性为错误时输入验证的边框颜色。",
  "dropdownBackground": "下拉列表背景色。",
  "dropdownListBackground": "下拉列表背景色。",
  "dropdownForeground": "下拉列表前景色。",
  "dropdownBorder": "下拉列表边框。",
  "checkbox.background": "复选框小部件的背景颜色。",
  "checkbox.foreground": "复选框小部件的前景色。",
  "checkbox.border": "复选框小部件的边框颜色。",
  "listFocusBackground": "焦点项在列表或树活动时的背景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listFocusForeground": "焦点项在列表或树活动时的背景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listActiveSelectionBackground": "已选项在列表或树活动时的背景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listActiveSelectionForeground": "已选项在列表或树活动时的前景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listInactiveSelectionBackground": "已选项在列表或树非活动时的背景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listInactiveSelectionForeground": "已选项在列表或树非活动时的前景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listInactiveFocusBackground": "非活动的列表或树控件中焦点项的背景颜色。活动的列表或树具有键盘焦点，非活动的没有。",
  "listHoverBackground": "使用鼠标移动项目时，列表或树的背景颜色。",
  "listHoverForeground": "鼠标在项目上悬停时，列表或树的前景颜色。",
  "listDropBackground": "使用鼠标移动项目时，列表或树进行拖放的背景颜色。",
  "highlight": "在列表或树中搜索时，其中匹配内容的高亮颜色。",
  "invalidItemForeground": "列表或树中无效项的前景色，例如资源管理器中没有解析的根目录。",
  "listErrorForeground": "包含错误的列表项的前景颜色。",
  "listWarningForeground": "包含警告的列表项的前景颜色。",
  "listFilterWidgetBackground": "列表和树中类型筛选器小组件的背景色。",
  "listFilterWidgetOutline": "列表和树中类型筛选器小组件的轮廓颜色。",
  "listFilterWidgetNoMatchesOutline": "当没有匹配项时，列表和树中类型筛选器小组件的轮廓颜色。",
  "treeIndentGuidesStroke": "缩进参考线的树描边颜色。",
  "pickerGroupForeground": "快速选取器分组标签的颜色。",
  "pickerGroupBorder": "快速选取器分组边框的颜色。",
  "buttonForeground": "按钮前景色。",
  "buttonBackground": "按钮背景色。",
  "buttonHoverBackground": "按钮在悬停时的背景颜色。",
  "badgeBackground": "Badge 背景色。Badge 是小型的信息标签，如表示搜索结果数量的标签。",
  "badgeForeground": "Badge 前景色。Badge 是小型的信息标签，如表示搜索结果数量的标签。",
  "scrollbarShadow": "表示视图被滚动的滚动条阴影。",
  "scrollbarSliderBackground": "滚动条滑块背景色",
  "scrollbarSliderHoverBackground": "滚动条滑块在悬停时的背景色",
  "scrollbarSliderActiveBackground": "滚动条滑块在被点击时的背景色。",
  "progressBarBackground": "表示长时间操作的进度条的背景色。",
  "menuBorder": "菜单的边框颜色。",
  "menuForeground": "菜单项的前景颜色。",
  "menuBackground": "菜单项的背景颜色。",
  "menuSelectionForeground": "菜单中选定菜单项的前景色。",
  "menuSelectionBackground": "菜单中所选菜单项的背景色。",
  "menuSelectionBorder": "菜单中所选菜单项的边框颜色。",
  "menuSeparatorBackground": "菜单中分隔线的颜色。",
  "editorError.foreground": "编辑器中错误波浪线的前景色。",
  "errorBorder": "编辑器中错误框的边框颜色。",
  "editorWarning.foreground": "编辑器中警告波浪线的前景色。",
  "warningBorder": "编辑器中警告框的边框颜色。",
  "editorInfo.foreground": "编辑器中信息波浪线的前景色。",
  "infoBorder": "编辑器中信息框的边框颜色。",
  "editorHint.foreground": "编辑器中提示波浪线的前景色。",
  "hintBorder": "编辑器中提示框的边框颜色。",
  "editorBackground": "编辑器背景色。",
  "editorForeground": "编辑器默认前景色。",
  "editorWidgetBackground": "编辑器组件(如查找/替换)背景颜色。",
  "editorWidgetForeground": "编辑器小部件的前景色，如查找/替换。",
  "editorWidgetBorder": "编辑器小部件的边框颜色。此颜色仅在小部件有边框且不被小部件重写时适用。",
  "editorWidgetResizeBorder": "编辑器小部件大小调整条的边框颜色。此颜色仅在小部件有调整边框且不被小部件颜色覆盖时使用。",
  "editorSelectionBackground": "编辑器所选内容的颜色。",
  "editorSelectionForeground": "用以彰显高对比度的所选文本的颜色。",
  "editorInactiveSelection": "非活动编辑器中所选内容的颜色，颜色必须透明，以免隐藏下面的装饰效果。",
  "editorSelectionHighlight": "具有与所选项相关内容的区域的颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "editorSelectionHighlightBorder": "与所选项内容相同的区域的边框颜色。",
  "editorFindMatch": "当前搜索匹配项的颜色。",
  "findMatchHighlight": "其他搜索匹配项的颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "findRangeHighlight": "限制搜索范围的颜色。颜色不能不透明，以免隐藏底层装饰。",
  "editorFindMatchBorder": "当前搜索匹配项的边框颜色。",
  "findMatchHighlightBorder": "其他搜索匹配项的边框颜色。",
  "findRangeHighlightBorder": "限制搜索的范围的边框颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "hoverHighlight": "在下面突出显示悬停的字词。颜色必须透明，以免隐藏下面的修饰效果。",
  "hoverBackground": "编辑器悬停提示的背景颜色。",
  "hoverBorder": "光标悬停时编辑器的边框颜色。",
  "statusBarBackground": "编辑器悬停状态栏的背景色。",
  "activeLinkForeground": "活动链接颜色。",
  "diffEditorInserted": "已插入的文本的背景色。颜色必须透明，以免隐藏下面的修饰效果。",
  "diffEditorRemoved": "已删除的文本的背景色。颜色必须透明，以免隐藏下面的修饰效果。",
  "diffEditorInsertedOutline": "插入的文本的轮廓颜色。",
  "diffEditorRemovedOutline": "被删除文本的轮廓颜色。",
  "diffEditorBorder": "两个文本编辑器之间的边框颜色。",
  "snippetTabstopHighlightBackground": "代码片段 Tab 位的高亮背景色。",
  "snippetTabstopHighlightBorder": "代码片段 Tab 位的高亮边框颜色。",
  "snippetFinalTabstopHighlightBackground": "代码片段中最后的 Tab 位的高亮背景色。",
  "snippetFinalTabstopHighlightBorder": "代码片段中最后的 Tab 位的高亮边框颜色。",
  "breadcrumbsFocusForeground": "焦点导航路径的颜色",
  "breadcrumbsBackground": "导航路径项的背景色。",
  "breadcrumbsSelectedForegound": "已选导航路径项的颜色。",
  "breadcrumbsSelectedBackground": "导航路径项选择器的背景色。",
  "mergeCurrentHeaderBackground": "当前标题背景的内联合并冲突。颜色不能不透明，以免隐藏底层装饰。",
  "mergeCurrentContentBackground": "内联合并冲突中的当前内容背景。颜色必须透明，以免隐藏下面的修饰效果。",
  "mergeIncomingHeaderBackground": "内联合并冲突中的传入标题背景。颜色必须透明，以免隐藏下面的修饰效果。",
  "mergeIncomingContentBackground": "内联合并冲突中的传入内容背景。颜色必须透明，以免隐藏下面的修饰效果。",
  "mergeCommonHeaderBackground": "内联合并冲突中的常见祖先标头背景。颜色必须透明，以免隐藏下面的修饰效果。",
  "mergeCommonContentBackground": "内联合并冲突中的常见祖先内容背景。颜色必须透明，以免隐藏下面的修饰效果。",
  "mergeBorder": "内联合并冲突中标头和分割线的边框颜色。",
  "overviewRulerCurrentContentForeground": "内联合并冲突中当前版本区域的概览标尺前景色。",
  "overviewRulerIncomingContentForeground": "内联合并冲突中传入的版本区域的概览标尺前景色。",
  "overviewRulerCommonContentForeground": "内联合并冲突中共同祖先区域的概览标尺前景色。",
  "overviewRulerFindMatchForeground": "用于查找匹配项的概述标尺标记颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "overviewRulerSelectionHighlightForeground": "用于突出显示所选内容的概述标尺标记颜色。颜色必须透明，以免隐藏下面的修饰效果。",
  "minimapFindMatchHighlight": "用于查找匹配项的迷你地图标记颜色。",
  "codeWorkspace": "Code 工作区"
};
